#!/bin/bash

log="/source/image/LOG";

error() { echo "!!!!! $1" && exit 1; }
info() { echo "*** $1"; }

verify() {
    if [[ "$1" -ne "0" ]]; then 
        error "!!!!! '$2'";
    fi;
}

##base
info "Install base packages";
apt-get -y update > $log 2>&1;
apt-get -y install software-properties-common git libgl1-mesa-dev > $log 2>&1;
verify "$?" "Unable to install base packages";  

##graphics
info "Install graphics packages";
apt-get -y install libglu1-mesa-dev freeglut3-dev mesa-common-dev > $log 2>&1;
verify "$?" "Unable to install graphics packages";

##python helpers
info "Install python helpers";
apt-get -y install python3-setuptools python3-dev > $log 2>&1;
verify "$?" "Unable to install python helpers";  

##pyglet
info "Install pyglet";
mkdir /pyglet;
cd /pyglet;
git clone https://github.com/pyglet/pyglet.git > $log 2>&1;
cd pyglet;
python3 setup.py install --user > $log 2>&1;

